name: Deploy to cPanel

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Adjust to the version you're using

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Push build to deploy branch
        run: |
          git checkout deploy
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          cp -r dist/* .  # Copy the build files to the root
          git add .
          git commit -m "Update build files"
          git push origin deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
