name: Publish Website to cPanel

on:
  pull_request:
    branches:
      - main
      - pre-prod

jobs:
  Deploy:
    name: Deploy to Server
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Inject API Key into .env
        run: |
          echo "VITE_GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> .env

      - name: Build Project
        run: npm run build

      - name: Copy .htaccess to Build Directory
        run: cp .htaccess ./dist/

      - name: Deploy to Pre Prod
        if: github.ref == 'refs/heads/pre-prod'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.PRE_PROD_FTP_USER }}
          password: ${{ secrets.PRE_PROD_FTP_PASS }}
          local-dir: ./dist/

      - name: Deploy to Prod
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USER }}
          password: ${{ secrets.PROD_FTP_PASS }}
          local-dir: ./dist/
