name: Enforce Merge From Pre-Prod

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from pre-prod
        run: |
          BASE_BRANCH=$(jq -r '.pull_request.base.ref' "$GITHUB_EVENT_PATH")
          HEAD_BRANCH=$(jq -r '.pull_request.head.ref' "$GITHUB_EVENT_PATH")

          echo "Base branch: $BASE_BRANCH"
          echo "Head branch: $HEAD_BRANCH"

          if [ "$BASE_BRANCH" = "main" ] && [ "$HEAD_BRANCH" = "pre-prod" ]; then
            echo "✅ Merge check passed!"
          else
            echo "❌ Merge to main is only allowed from pre-prod!"
            exit 1
          fi
